---
- name: Install Npm Unzip
  yum:
     name: "{{item}}"
     state: present
  with_items:
    - "unzip"
    - "npm"

- name: Install git2consul
  npm:
    name: git2consul
    global: yes

- name: Shutdown Consul
  shell: kill -9 $(ps -ef|grep consul|grep -v grep|awk '{print$2}')
  ignore_errors: true

- name: Download Consul k/v store
  get_url:
    url: https://releases.hashicorp.com/consul/{{consul_version}}/{{consul_name}}.zip
    dest: /tmp/{{consul_name}}.zip

- name: Unzip Consul
  shell: cd /tmp && unzip -d . {{consul_name}}.zip

- name: Move consul To /usr/bin
  shell: mv /tmp/consul /usr/bin/

- name: Create Config
  shell: mkdir -p {{consul_dir}}/conf

- name: Start Consul
  shell:  nohup /usr/bin/consul agent -server -data-dir={{consul_dir}} -node={{node_ip}} -bind={{bind_ip}} -datacenter={{dc}} -config-dir={{consul_dir}}/conf -ui -client=0.0.0.0 -bootstrap &
