---
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Install Docker.
  package: name={{ docker_package }} state=present

- name: add --insecure-registry 
  shell: sed -i 's/ExecStart=\/usr\/bin\/dockerd-current/ExecStart=\/usr\/bin\/dockerd-current --insecure-registry 192.168.100.3:5000/g' /usr/lib/systemd/system/docker.service 

- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: started
    enabled: yes

#- name: Install Docker Compose (if configured).
#  get_url:
#    url: https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64
#    dest: /usr/local/bin/docker-compose
#    mode: 0755
#  when: docker_install_compose
