---
- name: Install Python Jenkins Module
  pip: 
    name: python-jenkins 

- name: Create Pipeline Project
  jenkins_job:
     config: "{{ lookup('file', 'files/config.xml') }}"
     state: present
     name: "{{project_name}}"
     user: "{{user_name}}"
     password: "{{password}}"
     url: "{{jenkins_url}}:{{jenkins_port}}"
  ignore_errors: true

- name: Template Config
  template: src=config.xml dest={{jenkins_path}}/jobs/{{project_name}}/config.xml

- name: Restart Jenkins
  systemd: 
    name: jenkins
    state: restarted  
