- hosts: devtest 
  remote_user: vagrant
  become: yes
  vars:
   repo_url: "{{repo_url}}"
   project_name: "{{project_name}}"
   docker_registry: "{{docker_registry}}"
   consul_url: "{{consul_ip}}"
   consul_port: "{{consul_port}}"
   expose_port: "{{expose_port}}"
  roles:
    - pipeline_config
